deployment:
  tasks:
    - export DEPLOYPATH=/home/filokont/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -R actions assets config includes tools $DEPLOYPATH
    - /bin/cp *.php *.js *.sql *.md *.ini *.webmanifest $DEPLOYPATH
